[package]
name = "s3-proxy"
version = "0.1.0"
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]

[dependencies]
actix = "0.5"
actix-web = "0.6.4"
log = "0.4.1"
log4rs = "0.8.0"
rusoto_core = "0.32.0"
rusoto_s3 = "0.32.0"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4.6"
failure = "0.1.1"
futures = "0.1"
bytes = "0.4.6"
num_cpus = "1.8.0"
